### ISSUE TITLE
OpenBuilds MiniMill?

### ISSUE THREAD

**Issue by ahdinosaur** [hannobraun/cnc-mill#5]
stumbled upon this, might suit your needs? :robot: 

https://openbuilds.com/builds/openbuilds-minimill.5087/

available for purchase:

- (expensive) OpenBuilds Part Store: https://openbuildspartstore.com/openbuilds-minimill/
- BulkMan3D:
  - https://www.aliexpress.com/item/32848559381.html
  - https://www.aliexpress.com/item/32865931644.html
- you might find a local supplier (probably supplied by BulkMan3D), e.g. for me [MakerStore.au](https://www.makerstore.com.au/product/osm-mm01/)

**Comment by hannobraun** [comment]
Thank you, this does look cool! I'm doubtful that it's for me, for the following reasons:
- I was looking for something with a better work area to total size ratio though (which is why I'm looking into gantry-based designs).
- It's designed to work with a handheld router. I've heard those are very loud (which is a no-go for my use case), and they don't allow for software control of the spindle RPM.
- I see no indication on that page that it can cut aluminium, which I'd like to be capable of.

In addition, I absolutely need an enclosure, but that's not really an argument against this machine. I'll have to build my own with my own design too.

But it's definitely useful to see different designs, and what they are capable of. Seeing machines like this will certainly inform my own design decisions.

I've found this video about the mill, which I don't have time to watch right now: https://www.youtube.com/watch?v=4KVWpFGqT1I

I'll leave this issue open, until I had a chance to watch that video, and maybe look into the design some more.

**Comment by hannobraun** [comment]
I just finished watching that video. Conclusion: Without modifications, it can cut aluminium, but not well. He goes on to make a few modifications that make the machine much more capable.

This is an awesome video. I highly recommend it. Not only is it a great review (90% of it is cutting; none of that "man sitting in front of a machine, talking for 20 minutes"), he's also showing off the results for each modification, which is really interesting. Gave me a much better feeling for what rigidity means *specifically*. And now I better understand why everyone is raving about linear rails.

So thanks for nudging me in this direction, @ahdinosaur. Turned into some great learning!

**Comment by ahdinosaur** [comment]
>  I'm doubtful that it's for me, for the following reasons:

fair enough!

by the way, i found a more recent adaptation: "Millenium MiniMill" ([Reddit](https://www.reddit.com/r/MilleniumMachines/) / [Github](https://github.com/MilleniumMills/Millenium-Milo-v1.5)).

> So thanks for nudging me in this direction, @ahdinosaur. Turned into some great learning!

happy to hear these issues are helpful, i hope i'm not being annoying. :purple_heart:

**Comment by hannobraun** [comment]
> by the way, i found a more recent adaptation: "Millenium MiniMill" ([Reddit](https://www.reddit.com/r/MilleniumMachines/) / [Github](https://github.com/MilleniumMills/Millenium-Milo-v1.5)).

Nice, I'd seen that before! Of course I wasn't maintaining a research document at the time, so I promptly forgot again.

Seems much sturdier. There are some video of it cutting aluminium: https://www.youtube.com/channel/UCfdxXilZd76Dp8RfLxUJ_Gw/videos

Reopening this issue, until I've added it to my notes.

**Comment by hannobraun** [comment]
Oops, forgot to reply to a part of the message.

> happy to hear these issues are helpful, i hope i'm not being annoying. :purple_heart:

You're definitely not annoying! At this point in the process, I'm mostly just looking at stuff, and thinking about how it fits into what I want to build. Just seeing machines, how they're built, what kind of components they use, and where they land budget-wise, is extremely helpful.
